### ISSUE TITLE
Looking too far up tree

### ISSUE THREAD

**Issue by natew** [steelbrain/motion#425] opened 2017-04-13 23:38 UTC
Had a structure:

```
base
  node_modules/test
  app/
    web/
    node_modules/test
```

in `base/package.json` start script:

```
"web": "cd apps/web && npm start",
```

`npm run web`

Motion will actually use the `test` package from `base`, which was really confusing, rather than use the local test in `web`

**Comment by steelbrain** [comment] 2017-05-21 23:44
This is the known and expected behavior with deduping. It uses the version from `base` as long as semver allows it.

Closing as working as intended but feel free to continue discussing

**Closed by steelbrain** 2017-05-21 23:44 UTC
Labels: invalid
